#!/bin/bash

if [ -e "$LBPCONFIG/debmatic_installed" ]; then
	exit 0
fi

echo "<INFO> Installing Node-Red..."
/boot/dietpi/dietpi-software install 122

echo "<INFO> Installing Node-RED Nodes for the Homematic CCU..."
sudo -u nodered yes | npm --prefix mnt/dietpi_userdata/node-red install node-red-contrib-ccu

touch $LBPCONFIG/debmatic_installed

#rm $LBHOMEDIR/system/daemons/plugins/$0
reboot

exit 0
